language: php

php: 
  - 5.3
  - 5.4

branches:
  only:
    - master
    - develop
    - failure-demo

before_script:
  - curl http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: bin/phpspec run -v
